! 
! @OPENGROUP_COPYRIGHT@
! COPYRIGHT NOTICE
! Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
! Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
! ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
! the full copyright text.
! 
! This software is subject to an open license. It may only be
! used on, with or for operating systems which are themselves open
! source systems. You must contact The Open Group for a license
! allowing distribution and sublicensing of this software on, with,
! or for operating systems which are not Open Source programs.
! 
! See http://www.opengroup.org/openmotif/license for full
! details of the license agreement. Any use, reproduction, or
! distribution of the program constitutes recipient's acceptance of
! this agreement.
! 
! EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
! PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
! KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
! WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
! OR FITNESS FOR A PARTICULAR PURPOSE
! 
! EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
! NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
! INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
! DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
! AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
! LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
! ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
! EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
! POSSIBILITY OF SUCH DAMAGES.
! 
! 
! HISTORY
! 
!   $XConsortium: EnumVal6.msg /main/7 1995/07/13 20:28:04 drk $
!OSF/Motif: @(#)EnumVal6.msg	3.2  92/01/31
!
!  
!  	THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED
!  AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE AND
!  WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR
!  ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE
!  AVAILABLE TO ANY OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE
!  SOFTWARE IS HEREBY TRANSFERRED.
!  
!  	THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT
!  NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY OPEN SOFTWARE
!  
!  
!  
!  
!  
!  
!  
!  
!  
! DEC is a registered trademark of Digital Equipment Corporation
! DIGITAL is a registered trademark of Digital Equipment Corporation
!
value
  message :
	"Enumerated Values Test 6:\n\n" &
	"The following is a Bulletin Board set up to test correct\n" &
	"usage of enumeration values. (Note: this explanation text\n" &
	"itself tests the following:\n" &
	"  - XmNeditMode = XmMULTI_LINE_EDIT\n" &
	"Bulletin Board characteristics:\n" &
	"  - XmNborderWidth = 1\n" &
	"  - XmNbackground =  sky_blue\n" &
	"  - XmNmarginWidth =  20\n" &
	"  - XmNmarginHeight =  20\n" &
	"  - XmNdefaultPosition =  false\n" &
	"  - XmNnoResize =  true\n" &
	"  - XmNResizePolicy = XmRESIZE_GROW\n" &
	"  - XmNshadowType = XmSHADOW_ETCHED_OUT\n" &
	"  - XmNshadowThickness = 10\n" &
	"Form charactereristics:\n" &
	"  - XmNx = 30\n" &
	"  - XmNy = 30\n" &
	"  - XmNwidth = 300\n" &
	"  - XmNheight = 150\n" &
	"  - XmNborderWidth = 2\n" &
	"  - XmNresizePolicy = XmRESIZE_GROW\n" &
	"  Form children:\n" &
	"    Toggle 1:\n" &
	"      - XmNleftAttachment = XmATTACH_FORM\n" &
	"      - XmNleftOffset = 10\n" &
	"      - XmNtopAttachment = XmATTACH_POSITION\n" &
	"      - XmNtopPosition = 10\n" &
	"      - XmNlabelString = Toggle 1 (with a longer name)\n" &
	"      - XmNshadowThickness = 2\n" &
	"      - XmNborderWidth = 1\n" &
	"    Toggle 2:\n" &
	"      - XmNbottomAttachment = XmATTACH_OPPOSITE_FORM\n" &
	"      - XmNbottomOffset = -90\n" &
	"      - XmNrightAttachment = XmATTACH_OPPOSITE_WIDGET\n" &
	"      - XmNrightWidget = XmToggleButton ToggleButtonF1\n" &
	"      - XmNindicatorType = XmN_OF_MANY\n" &
	"      - XmNlabelString = Toggle 2 (shorter name)\n" &
	"      - XmNshadowThickness = 2\n" &
	"      - XmNborderWidth = 1\n" &
	"    Toggle 3:\n" &
	"      - XmNtopAttachment = XmATTACH_WIDGET\n" &
	"      - XmNtopWidget = XmToggleButton ToggleButtonF2\n" &
	"      - XmNtopOffset = 10\n" &
	"      - XmNleftAttachment = XmATTACH_WIDGET\n" &
	"      - XmNleftWidget = XmToggleButton ToggleButtonF2\n" &
	"      - XmNbottomAttachment = XmATTACH_FORM\n" &
	"      - XmNbottomOffset = 10\n" &
	"      - XmNindicatorType = XmONE_OF_MANY\n" &
	"      - XmNlabelString = Toggle 3\n" &
	"      - XmNshadowThickness = 2\n" &
	"      - XmNborderWidth = 1";
