#!/bin/csh
# @OPENGROUP_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
# ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
# the full copyright text.
# 
# This software is subject to an open license. It may only be
# used on, with or for operating systems which are themselves open
# source systems. You must contact The Open Group for a license
# allowing distribution and sublicensing of this software on, with,
# or for operating systems which are not Open Source programs.
# 
# See http://www.opengroup.org/openmotif/license for full
# details of the license agreement. Any use, reproduction, or
# distribution of the program constitutes recipient's acceptance of
# this agreement.
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
# PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
# WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
# OR FITNESS FOR A PARTICULAR PURPOSE
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
# NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
# EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES.
# 
# HISTORY
#
# This is the script to create links to a predefined subset of the
# test suite (.c .dat and .scr files only) before any configuration RUN.
#

if ( "$1" == "-undo" ) then 
	set mode = "-undo"
else
	set mode = "-do"
endif

set LIST="../Menus Menu1 MenuBar1 OptionMenu1 PopupMenu1 -next \
../Text Text1 Text2 TextField2 TextField3 ScrollText1 ScrollText2 -next\
../Traversal Navigation3 Navigation12 -next\
../List List1 List2 -next\
../Buttons ArrowBGad1 PushBGad2 ToggleBGad1 ArrowBtn1 PushBtn1 ToggleBtn1 -next\
../Select Command2 FileSelect2 PromptDia1 SelectBox2 -next\
../Primitive Label1 LabelGad1 -next\
../Scrollbar Scale1 Scale3 Scrollbar1 Scrollbar2 -next\
../Shells DiaShell1 Protocol -next\
../Windows MainWin2 ScrollWin1"

set DIR=""
foreach i ( $LIST )
	if ( "$DIR" == "" ) then 
		set DIR = "$i"
	else
		if ( "$i" == "-next" ) then 
			set DIR = ""
		else
			if ( "$mode" == "-do" ) then
#set verbose
				rm -f C$i.c; ln -s $DIR/$i.c C$i.c
				rm -f C$i.dat; ln -s $DIR/$i.dat C$i.dat
				rm -f C$i.scr; ln -s $DIR/$i.scr C$i.scr
#unset verbose
			else if ( "$mode" == "-undo" ) then
#set verbose
				rm -f C$i.c; rm -f C$i.dat; rm -f C$i.scr
#unset verbose
			endif
		endif
	endif
end

#
# Create links for certain needed header files also
#
if ( "$mode" == "-do" ) then
	rm -f List1.h; ln -s ../List/List1.h List1.h
	rm -f List2.h; ln -s ../List/List2.h List2.h
	rm -f TextField1.h; ln -s ../Text/TextField1.h TextField1.h
else if ( "$mode" == "-undo" ) then
	rm -f List1.h
	rm -f List2.h
	rm -f TextField1.h
endif
