#!/bin/csh

# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
# ALL RIGHTS RESERVED (MOTIF).  See the file named COPYRIGHT.MOTIF for
# the full copyright text.
# 
# This software is subject to an open license. It may only be
# used on, with or for operating systems which are themselves open
# source systems. You must contact The Open Group for a license
# allowing distribution and sublicensing of this software on, with,
# or for operating systems which are not Open Source programs.
# 
# See http://www.opengroup.org/openmotif/license for full
# details of the license agreement. Any use, reproduction, or
# distribution of the program constitutes recipient's acceptance of
# this agreement.
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
# PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
# WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
# OR FITNESS FOR A PARTICULAR PURPOSE
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
# NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
# EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES.
# 
# 
# HISTORY
# @OPENGROUP_COPYRIGHT@
#

# This script runs all the automated QATS tests, as defined in the file
# ./tests/General/dirsAuto

unalias cd
unalias pushd
unalias popd

set dirs_file = ../tests/General/dirsAuto
set DIR_LIST = (`cat $dirs_file`)
set TESTS_HOME = $cwd

echo  $#DIR_LIST " directories of automated tests to be run..."

# Go to the lib dir and build the Motif libraries local

cd $TESTS_HOME/../lib
echo "I am in " $cwd

set DIR = $cwd:t
if (-e make.$DIR) then
	mv  make.$DIR make.$DIR.bak
endif
make -i >& make.$DIR

# Go to each automated test directory

foreach dir ($DIR_LIST)
        cd $TESTS_HOME/../$dir
	set DIR = $cwd:t
        echo "I am in " $cwd

# Make all the automated tests and supporting files in this directory

        if (-e make.$DIR) then
                mv  make.$DIR make.$DIR.bak
        endif
        make IMAKE_DEFINES=-DAUTOMATION Makefile
        make -i >& make.$DIR

# Use the generated RUN script to run all of the tests

        if (-e RUN.$DIR) then
            if (-e RUN.$DIR.bak) then
                rm -f RUN.$DIR.bak
            endif
            mv RUN.$DIR RUN.$DIR.bak
        endif
        RUN -T -D 1 -genrep -Dir -d :0.0 >& RUN.$DIR

# Clean up the directory before leaving

        make clean

end
