#!/bin/sh
# @OPENGROUP_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
# ALL RIGHTS RESERVED (MOTIF).  See the file named COPYRIGHT.MOTIF for
# the full copyright text.
# 
# This software is subject to an open license. It may only be
# used on, with or for operating systems which are themselves open
# source systems. You must contact The Open Group for a license
# allowing distribution and sublicensing of this software on, with,
# or for operating systems which are not Open Source programs.
# 
# See http://www.opengroup.org/openmotif/license for full
# details of the license agreement. Any use, reproduction, or
# distribution of the program constitutes recipient's acceptance of
# this agreement.
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
# PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
# WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
# OR FITNESS FOR A PARTICULAR PURPOSE
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
# NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
# EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES.
# 
# 
# HISTORY

if (test $# -lt 1)
then
        language=american
	testcase=a
else
        language=$1
	testcase=$2
fi

if [ -n "$(whence uname)" ]
then 
	sysname=`uname -s`
else
	sysname="unix"
fi

case $sysname in
	HP-UX | ULTRIX | OSF1 )
	echo Operating System is $sysname
	;;
	* )
	echo Operating System is unknown !!!
	echo You should update xmfile script to support your OS
	;;
esac

case $language in
  french)
        XAPPLRESDIR=`pwd`/french
	case $sysname in
	HP-UX)
		LANG=french.iso88591
		;;
	* )
		LANG=french
		;;
	esac
	;;

  english | american )
        XAPPLRESDIR=`pwd`/american
        case $sysname in
	HP-UX)
		LANG=american
		;;
	* )
		LANG=american
		;;
	esac
	;;

  hebrew)
        XAPPLRESDIR=`pwd`/hebrew
        case $sysname in
	HP-UX)
		LANG=hebrew
		;;
	* )
		LANG=hebrew
		;;
	esac
	;;

  japanese)
        XAPPLRESDIR=`pwd`/japanese
        case $sysname in
	HP-UX)
		LANG=japanese
		;;
	* )
		LANG=japanese
		;;
	esac
	;;

  japanese.euc)
        XAPPLRESDIR=`pwd`/japanese/euc
        case $sysname in
	HP-UX)
		LANG=japanese.euc
		;;
	* )
		LANG=japanese
		;;
	esac
	;;

  korean)
        XAPPLRESDIR=`pwd`/korean
        case $sysname in
	HP-UX)
		LANG=korean
		;;
	* )
		LANG=korean
		;;
	esac
	;;

  * )
	echo unknown language $language -- try running in C locale
        XAPPLRESDIR=`pwd`
	unset LANG
	;;	
esac

XFILESEARCHPATH=$XAPPLRESDIR/I18N.defaults:$XFILESEARCHPATH 

export XFILESEARCHPATH LANG XAPPLRESDIR

I18N1 -I $XAPPLRESDIR/I18N1$testcase.Dat -u $testcase
