#!/bin/csh
# @OPENGROUP_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
# ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
# the full copyright text.
# 
# This software is subject to an open license. It may only be
# used on, with or for operating systems which are themselves open
# source systems. You must contact The Open Group for a license
# allowing distribution and sublicensing of this software on, with,
# or for operating systems which are not Open Source programs.
# 
# See http://www.opengroup.org/openmotif/license for full
# details of the license agreement. Any use, reproduction, or
# distribution of the program constitutes recipient's acceptance of
# this agreement.
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
# PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
# WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
# OR FITNESS FOR A PARTICULAR PURPOSE
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
# NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
# EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES.
#
# HISTORY

# 
#	This shell script will run the noninteractive Mrm tests FetchL
#	RegisterN, HierN and make FetchWloop.uid and redirect the output
#	to the file	'nonint.out'
#

if (-e nonint.out) then
	mv nonint.out nonint.out.bk
endif

echo ""
echo "Running the noninteractive Mrm tests FetchL, RegisterN, HierN and"
echo "	make FetchWloop.uid."
echo "Output will be redirected to the file nonint.out."

echo "These are the results of the noninteractive Mrm tests:" > nonint.out
echo "" >> nonint.out
echo "" >> nonint.out

echo "	."
echo >> nonint.out
echo "------------------------------------ FetchL ------------------------------------" >> nonint.out

FetchL $* >>& nonint.out 

echo "	."
echo >> nonint.out
echo "---------------------------------- RegisterN -----------------------------------" >> nonint.out

RegisterN $* >>& nonint.out 

echo "	."
echo >> nonint.out
echo "------------------------------------ HierN -------------------------------------" >> nonint.out

HierN $* >>& nonint.out 

echo "	."
echo >> nonint.out
echo "------------------------------- make FetchWloop.uid ---------------------------" >> nonint.out

#remove all other core files so later test works
echo "Removing any existing core files" >> nonint.out
if (-e core) then
   rm core
endif

../.././clients/uil/uil -o FetchWloop.uid FetchWloop.uil  -I../.././clients/uil  FetchWloop.uid >>& nonint.out 

set makestatus = $status

if ($makestatus == 1) then
   echo " " >> nonint.out
   echo "FetchWloop test PASSES" >> nonint.out
endif
if (($makestatus == 0) || (($makestatus <= 4) && ($makestatus > 1))) then
	echo "FetchWloop test FAILS" >> nonint.out
endif 
if ($makestatus > 4) then
  echo "FetchWloop test FAILS BADLY. " >> nonint.out
  if (-e core) then
   echo "A core file exists. This test may have died fatally." >> nonint.out
   echo "Please compile the file FetchWloop.uil manually." >> nonint.out
  endif
endif

echo " " >>& nonint.out
echo " " >>& nonint.out

echo "The noninteractive Mrm tests have completed."
echo ""

#
#  End Run script
#
