#!/bin/sh
# @OPENGROUP_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
# ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
# the full copyright text.
# 
# This software is subject to an open license. It may only be
# used on, with or for operating systems which are themselves open
# source systems. You must contact The Open Group for a license
# allowing distribution and sublicensing of this software on, with,
# or for operating systems which are not Open Source programs.
# 
# See http://www.opengroup.org/openmotif/license for full
# details of the license agreement. Any use, reproduction, or
# distribution of the program constitutes recipient's acceptance of
# this agreement.
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
# PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
# WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
# OR FITNESS FOR A PARTICULAR PURPOSE
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
# NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
# EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES.
#
# HISTORY

# 
#	This shell script will run the interactive Mrm tests 
#	CloseH, FetchCL, FetchIL, FetchSV, FetchW, 
#	FetchWO, OpenH, and RegisterC.
#

echo ""
echo "Running the interactive Mrm tests "
echo "   CloseH, FetchCL, FetchIL, FetchSV, FetchW, "
echo "   FetchWO, OpenH, and RegisterC. "
echo "Summary output will be redirected to the file intsum.out."

echo "These are the results of the interactive Mrm tests:" > intsum.out
echo "" >> intsum.out
echo "" >> intsum.out

echo "	."
echo "------------------------------------ CloseH ------------------------------------" >> intsum.out

CloseH $* >> intsum.out

echo "	."
echo "------------------------------------ FetchCL ------------------------------------" >> intsum.out

FetchCL $* >> intsum.out

echo "	."
echo "------------------------------------ FetchIL ------------------------------------" >> intsum.out

FetchIL $* >> intsum.out

echo "	."
echo "------------------------------------ FetchSV ------------------------------------" >> intsum.out

FetchSV $* >> intsum.out

echo "	."
echo "------------------------------------ FetchW ------------------------------------" >> intsum.out

FetchW $* >> intsum.out

echo "	."
echo "------------------------------------ FetchWO ------------------------------------" >> intsum.out

FetchWO $* >> intsum.out

echo "	."
echo "------------------------------------ OpenH ------------------------------------" >> intsum.out
echo "This test sets the LANG environment variable to OpenHLang" >> intsum.out
set LANG=OpenHLang
OpenH $* >> intsum.out

echo "	."
echo "------------------------------------ RegisterC ------------------------------------" >> intsum.out

RegisterC $* >> intsum.out

echo "The interactive Mrm tests have completed."
echo ""

#
#  End Run script
#





