#!/bin/sh
# @OPENGROUP_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# Copyright (c) 1996, 1997, 1998, 1999, 2000 The Open Group
# ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
# the full copyright text.
# 
# This software is subject to an open license. It may only be
# used on, with or for operating systems which are themselves open
# source systems. You must contact The Open Group for a license
# allowing distribution and sublicensing of this software on, with,
# or for operating systems which are not Open Source programs.
# 
# See http://www.opengroup.org/openmotif/license for full
# details of the license agreement. Any use, reproduction, or
# distribution of the program constitutes recipient's acceptance of
# this agreement.
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS
# PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY
# WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
# OR FITNESS FOR A PARTICULAR PURPOSE
# 
# EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT
# NOR ANY CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
# EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES.
#
# HISTORY

#
#	Script to reproduce PIR 2793
#
#	To run this program type 'nohup behavior_test'
#
#	Related files forthis test are:
#	
#		./behavior.xinit
#		./behavior.Xdefs
#		./behavior.mwmrc
#

SYSTEM=`uname -a | awk -F' ' '{print $1}'`
CURR_DIR=`pwd`
XENVIRONMENT=`pwd`

# get the xinit process and kill it
#	look for " xinit" or ".../xinit"
#	this should give you only things that really are xinit
#	remove all leading whitespace and replace multiple
#	tabs/spaces with 1 space
if [ ${SYSTEM} = "HP-UX" ]
then
# HP version
	X_LINE=`ps -ef | grep X | egrep -v "xinit|grep"`
	BETTER_X_LINE=`echo ${X_LINE} | sed -e 's/^[	 ]*//
		s/[	 ][	 ]*/ /g'`
	X_PID=`echo ${BETTER_X_LINE} | cut -d' ' -f2`
else
# others, like DEC version
    X_LINE=`ps -axw | grep X | egrep -v "xinit|grep"`
	BETTER_X_LINE=`echo ${X_LINE} | sed -e 's/^[   ]*//
		s/[  ][  ]*/ /g'`
	X_PID=`echo ${BETTER_X_LINE} | cut -d' ' -f1`
fi

	kill ${X_PID}
# start new X session
	sleep 5
#
xinit ${CURR_DIR}/behavior.xinit
# end of script
