.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmDropDownGetText" "library call"
.SH "NAME"
\fBXmDropDownGetText\fP \(em A DropDown function that returns the "text" child of
the XmDropDown
.iX "XmDropDownGetText"
.iX "DropDown functions" "XmDropDownGetText"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DropDown\&.h>
\fBWidget \fBXmDropDownGetText\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmDropDownGetText\fP is used to access the "text" child within the
DropDown widget\&.
.IP "\fIwidget\fP" 10
Specifies the DropDown widget ID\&.
.PP
For a complete definition of DropDown and its associated resources, see
\fBXmDropDown\fP(3)\&.
.SH "RETURN"
.PP
Returns the widget ID of the "text" child of the DropDown widget\&.
.SH "RELATED"
.PP
\fBXmDropDown\fP(3)\&.
