.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmDropDownGetArrow" "library call"
.SH "NAME"
\fBXmDropDownGetArrow\fP \(em A DropDown function that returns the "arrow" child of
the XmDropDown
.iX "XmDropDownGetArrow"
.iX "DropDown functions" "XmDropDownGetArrow"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DropDown\&.h>
\fBWidget \fBXmDropDownGetArrow\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmDropDownGetArrow\fP is used to access the "arrow" child within the
DropDown widget\&.
.IP "\fIwidget\fP" 10
Specifies the DropDown widget ID\&.
.PP
For a complete definition of DropDown and its associated resources, see
\fBXmDropDown\fP(3)\&.
.SH "RETURN"
.PP
Returns the widget ID of the "arrow" child of the DropDown widget\&.
.SH "RELATED"
.PP
\fBXmDropDown\fP(3)\&.
