/*
**	This file is automatically generated.  Do not edit it by hand.
**/

/*
 * Enumeration value vectors for each enumeration set
 */


static unsigned short int enum_value_vec1[] =
  {
    56,
    59,
    55,
  };

static unsigned short int enum_value_vec2[] =
  {
    81,
    78,
    79,
    80,
  };

static unsigned short int enum_value_vec3[] =
  {
    69,
    66,
    76,
    71,
    70,
  };

static unsigned short int enum_value_vec4[] =
  {
    77,
    72,
  };

static unsigned short int enum_value_vec5[] =
  {
    74,
    73,
    67,
    75,
    68,
  };

static unsigned short int enum_value_vec6[] =
  {
    85,
    84,
    86,
    90,
    87,
    88,
    89,
  };

static unsigned short int enum_value_vec7[] =
  {
    233,
    97,
  };

static unsigned short int enum_value_vec8[] =
  {
    93,
    92,
  };

static unsigned short int enum_value_vec9[] =
  {
    236,
    94,
    23,
    45,
  };

static unsigned short int enum_value_vec10[] =
  {
    44,
    46,
    1,
  };

static unsigned short int enum_value_vec11[] =
  {
    314,
    316,
    268,
  };

static unsigned short int enum_value_vec12[] =
  {
    23,
    45,
  };

static unsigned short int enum_value_vec13[] =
  {
    273,
    271,
    272,
  };

static unsigned short int enum_value_vec14[] =
  {
    54,
    56,
    53,
    61,
    62,
  };

static unsigned short int enum_value_vec15[] =
  {
    209,
    338,
  };

static unsigned short int enum_value_vec16[] =
  {
    111,
    149,
    150,
  };

static unsigned short int enum_value_vec17[] =
  {
    112,
    113,
  };

static unsigned short int enum_value_vec18[] =
  {
    332,
    321,
    331,
    322,
    329,
    326,
    325,
    333,
    324,
    323,
    327,
    328,
    330,
  };

static unsigned short int enum_value_vec19[] =
  {
    375,
    374,
  };

static unsigned short int enum_value_vec20[] =
  {
    306,
  };

static unsigned short int enum_value_vec21[] =
  {
    121,
    123,
    127,
    130,
    132,
    137,
    138,
  };

static unsigned short int enum_value_vec22[] =
  {
    118,
    376,
    148,
  };

static unsigned short int enum_value_vec23[] =
  {
    139,
    133,
    131,
    143,
    126,
    120,
  };

static unsigned short int enum_value_vec24[] =
  {
    134,
    136,
    143,
    125,
    124,
    128,
    129,
    135,
    141,
    142,
    140,
    122,
  };

static unsigned short int enum_value_vec25[] =
  {
    19,
    18,
    20,
  };

static unsigned short int enum_value_vec26[] =
  {
    4,
    5,
    6,
    3,
  };

static unsigned short int enum_value_vec27[] =
  {
    13,
    12,
    11,
    10,
    9,
  };

static unsigned short int enum_value_vec28[] =
  {
    7,
    8,
    2,
  };

static unsigned short int enum_value_vec29[] =
  {
    16,
    17,
    14,
    15,
  };

static unsigned short int enum_value_vec30[] =
  {
    310,
    156,
  };

static unsigned short int enum_value_vec31[] =
  {
    309,
    230,
  };

static unsigned short int enum_value_vec32[] =
  {
    201,
    312,
    63,
  };

static unsigned short int enum_value_vec33[] =
  {
    159,
    158,
    157,
  };

static unsigned short int enum_value_vec34[] =
  {
    175,
    173,
    174,
    172,
  };

static unsigned short int enum_value_vec35[] =
  {
    82,
    165,
    166,
  };

static unsigned short int enum_value_vec36[] =
  {
    169,
    171,
    170,
  };

static unsigned short int enum_value_vec37[] =
  {
    95,
    254,
    116,
    183,
  };

static unsigned short int enum_value_vec38[] =
  {
    201,
    312,
  };

static unsigned short int enum_value_vec39[] =
  {
    200,
    196,
    199,
    195,
    198,
    197,
  };

static unsigned short int enum_value_vec40[] =
  {
    242,
    244,
    246,
    245,
  };

static unsigned short int enum_value_vec41[] =
  {
    43,
    24,
  };

static unsigned short int enum_value_vec42[] =
  {
    260,
    261,
    193,
  };

static unsigned short int enum_value_vec43[] =
  {
    203,
    284,
    363,
    98,
  };

static unsigned short int enum_value_vec44[] =
  {
    155,
    274,
  };

static unsigned short int enum_value_vec45[] =
  {
    320,
    263,
  };

static unsigned short int enum_value_vec46[] =
  {
    287,
    206,
    286,
    205,
    368,
    367,
    103,
    102,
    366,
    101,
    285,
    204,
    117,
  };

static unsigned short int enum_value_vec47[] =
  {
    247,
    315,
    119,
  };

static unsigned short int enum_value_vec48[] =
  {
    82,
    308,
    147,
    307,
    146,
    237,
  };

static unsigned short int enum_value_vec49[] =
  {
    115,
    380,
    282,
  };

static unsigned short int enum_value_vec50[] =
  {
    82,
    208,
    207,
  };

static unsigned short int enum_value_vec51[] =
  {
    278,
    194,
  };

static unsigned short int enum_value_vec52[] =
  {
    227,
    228,
  };

static unsigned short int enum_value_vec53[] =
  {
    28,
    29,
    33,
    34,
    31,
    32,
    30,
  };

static unsigned short int enum_value_vec54[] =
  {
    35,
    38,
    37,
    32,
    30,
    36,
  };

static unsigned short int enum_value_vec55[] =
  {
    40,
    41,
    42,
    39,
  };

static unsigned short int enum_value_vec56[] =
  {
    233,
    355,
    319,
    153,
  };

static unsigned short int enum_value_vec57[] =
  {
    258,
    210,
    225,
    318,
    259,
  };

static unsigned short int enum_value_vec58[] =
  {
    51,
    279,
  };

static unsigned short int enum_value_vec59[] =
  {
    238,
    381,
    181,
  };

static unsigned short int enum_value_vec60[] =
  {
    249,
    248,
  };

static unsigned short int enum_value_vec61[] =
  {
    110,
    154,
  };

static unsigned short int enum_value_vec62[] =
  {
    239,
    257,
    255,
    256,
  };

static unsigned short int enum_value_vec63[] =
  {
    202,
    164,
  };

static unsigned short int enum_value_vec64[] =
  {
    384,
    243,
  };

static unsigned short int enum_value_vec65[] =
  {
    276,
    277,
  };

static unsigned short int enum_value_vec66[] =
  {
    252,
    250,
    251,
    253,
  };

static unsigned short int enum_value_vec67[] =
  {
    217,
    214,
    215,
    216,
  };

static unsigned short int enum_value_vec68[] =
  {
    283,
    280,
    281,
  };

static unsigned short int enum_value_vec69[] =
  {
    383,
    219,
    222,
    221,
    220,
  };

static unsigned short int enum_value_vec70[] =
  {
    233,
    232,
    231,
    23,
    45,
  };

static unsigned short int enum_value_vec71[] =
  {
    83,
    317,
  };

static unsigned short int enum_value_vec72[] =
  {
    364,
    99,
    365,
    100,
  };

static unsigned short int enum_value_vec73[] =
  {
    182,
    382,
    114,
    223,
    289,
    290,
    240,
    108,
    176,
  };

static unsigned short int enum_value_vec74[] =
  {
    91,
    65,
  };

static unsigned short int enum_value_vec75[] =
  {
    234,
    52,
  };

static unsigned short int enum_value_vec76[] =
  {
    310,
    229,
    156,
    104,
  };

static unsigned short int enum_value_vec77[] =
  {
    211,
    213,
    212,
    369,
    370,
  };

static unsigned short int enum_value_vec78[] =
  {
    308,
    147,
    307,
    146,
    237,
    300,
    302,
    301,
    303,
  };

static unsigned short int enum_value_vec79[] =
  {
    304,
    305,
    300,
    302,
  };

static unsigned short int enum_value_vec80[] =
  {
    151,
    218,
    226,
    23,
    45,
  };

static unsigned short int enum_value_vec81[] =
  {
    21,
    22,
  };

static unsigned short int enum_value_vec82[] =
  {
    233,
    152,
    360,
    288,
  };

static unsigned short int enum_value_vec83[] =
  {
    96,
    168,
    371,
    299,
  };

static unsigned short int enum_value_vec84[] =
  {
    311,
    359,
  };

static unsigned short int enum_value_vec85[] =
  {
    64,
    109,
    163,
  };

static unsigned short int enum_value_vec86[] =
  {
    180,
    179,
    178,
  };

static unsigned short int enum_value_vec87[] =
  {
    233,
    313,
    106,
  };

static unsigned short int enum_value_vec88[] =
  {
    233,
    177,
    105,
  };

static unsigned short int enum_value_vec89[] =
  {
    320,
    241,
  };

static unsigned short int enum_value_vec90[] =
  {
    335,
    336,
  };

static unsigned short int enum_value_vec91[] =
  {
    358,
    357,
  };

static unsigned short int enum_value_vec92[] =
  {
    335,
    336,
    337,
    334,
    117,
  };

static unsigned short int enum_value_vec93[] =
  {
    295,
    296,
    297,
    293,
    292,
    294,
  };

static unsigned short int enum_value_vec94[] =
  {
    192,
    191,
    186,
    187,
    188,
    189,
    190,
    23,
    45,
  };

static unsigned short int enum_value_vec95[] =
  {
    361,
    362,
  };

static unsigned short int enum_value_vec96[] =
  {
    379,
    298,
    185,
    23,
    45,
  };

static unsigned short int enum_value_vec97[] =
  {
    262,
    49,
    47,
    50,
    48,
    184,
    107,
    224,
    275,
    167,
  };

static unsigned short int enum_value_vec98[] =
  {
    378,
    377,
  };

static unsigned short int enum_value_vec99[] =
  {
    54,
    56,
    53,
    58,
    57,
  };

static unsigned short int enum_value_vec100[] =
  {
    291,
    235,
  };

static unsigned short int enum_value_vec101[] =
  {
    380,
    115,
  };

static unsigned short int enum_value_vec102[] =
  {
    55,
    56,
    59,
    60,
  };

static unsigned short int enum_value_vec103[] =
  {
    145,
    144,
  };

static unsigned short int enum_value_vec104[] =
  {
    162,
    160,
    161,
  };

static unsigned short int enum_value_vec105[] =
  {
    270,
    264,
    269,
    265,
    266,
    267,
  };

static unsigned short int enum_value_vec106[] =
  {
    354,
    353,
  };

static unsigned short int enum_value_vec107[] =
  {
    339,
    350,
    351,
  };

static unsigned short int enum_value_vec108[] =
  {
    356,
    347,
    342,
    352,
    341,
  };

static unsigned short int enum_value_vec109[] =
  {
    346,
    343,
    345,
    344,
  };

static unsigned short int enum_value_vec110[] =
  {
    349,
    348,
    340,
  };

static unsigned short int enum_value_vec111[] =
  {
    373,
    372,
    372,
  };

static unsigned short int enum_value_vec112[] =
  {
    27,
    26,
    25,
  };

/*
 * Enumeration set descriptor table
 */
static UilEnumSetDescDef enum_set_table_vec[] =
  {
    {0,NULL},
    {3,enum_value_vec1},
    {4,enum_value_vec2},
    {5,enum_value_vec3},
    {2,enum_value_vec4},
    {5,enum_value_vec5},
    {7,enum_value_vec6},
    {2,enum_value_vec7},
    {2,enum_value_vec8},
    {4,enum_value_vec9},
    {3,enum_value_vec10},
    {3,enum_value_vec11},
    {2,enum_value_vec12},
    {3,enum_value_vec13},
    {5,enum_value_vec14},
    {2,enum_value_vec15},
    {3,enum_value_vec16},
    {2,enum_value_vec17},
    {13,enum_value_vec18},
    {2,enum_value_vec19},
    {1,enum_value_vec20},
    {7,enum_value_vec21},
    {3,enum_value_vec22},
    {6,enum_value_vec23},
    {12,enum_value_vec24},
    {3,enum_value_vec25},
    {4,enum_value_vec26},
    {5,enum_value_vec27},
    {3,enum_value_vec28},
    {4,enum_value_vec29},
    {2,enum_value_vec30},
    {2,enum_value_vec31},
    {3,enum_value_vec32},
    {3,enum_value_vec33},
    {4,enum_value_vec34},
    {3,enum_value_vec35},
    {3,enum_value_vec36},
    {4,enum_value_vec37},
    {2,enum_value_vec38},
    {6,enum_value_vec39},
    {4,enum_value_vec40},
    {2,enum_value_vec41},
    {3,enum_value_vec42},
    {4,enum_value_vec43},
    {2,enum_value_vec44},
    {2,enum_value_vec45},
    {13,enum_value_vec46},
    {3,enum_value_vec47},
    {6,enum_value_vec48},
    {3,enum_value_vec49},
    {3,enum_value_vec50},
    {2,enum_value_vec51},
    {2,enum_value_vec52},
    {7,enum_value_vec53},
    {6,enum_value_vec54},
    {4,enum_value_vec55},
    {4,enum_value_vec56},
    {5,enum_value_vec57},
    {2,enum_value_vec58},
    {3,enum_value_vec59},
    {2,enum_value_vec60},
    {2,enum_value_vec61},
    {4,enum_value_vec62},
    {2,enum_value_vec63},
    {2,enum_value_vec64},
    {2,enum_value_vec65},
    {4,enum_value_vec66},
    {4,enum_value_vec67},
    {3,enum_value_vec68},
    {5,enum_value_vec69},
    {5,enum_value_vec70},
    {2,enum_value_vec71},
    {4,enum_value_vec72},
    {9,enum_value_vec73},
    {2,enum_value_vec74},
    {2,enum_value_vec75},
    {4,enum_value_vec76},
    {5,enum_value_vec77},
    {9,enum_value_vec78},
    {4,enum_value_vec79},
    {5,enum_value_vec80},
    {2,enum_value_vec81},
    {4,enum_value_vec82},
    {4,enum_value_vec83},
    {2,enum_value_vec84},
    {3,enum_value_vec85},
    {3,enum_value_vec86},
    {3,enum_value_vec87},
    {3,enum_value_vec88},
    {2,enum_value_vec89},
    {2,enum_value_vec90},
    {2,enum_value_vec91},
    {5,enum_value_vec92},
    {6,enum_value_vec93},
    {9,enum_value_vec94},
    {2,enum_value_vec95},
    {5,enum_value_vec96},
    {10,enum_value_vec97},
    {2,enum_value_vec98},
    {5,enum_value_vec99},
    {2,enum_value_vec100},
    {2,enum_value_vec101},
    {4,enum_value_vec102},
    {2,enum_value_vec103},
    {3,enum_value_vec104},
    {6,enum_value_vec105},
    {2,enum_value_vec106},
    {3,enum_value_vec107},
    {5,enum_value_vec108},
    {4,enum_value_vec109},
    {3,enum_value_vec110},
    {3,enum_value_vec111},
    {3,enum_value_vec112},
  };
externaldef(uil_sym_glbl) UilEnumSetDescDef *enum_set_table =
		enum_set_table_vec;
/*
 * Enumeration set table, accessed by sym_k_..._arg code. Each non-zero entry
 * is the sym_k_..._enumset code for the argument's enumeration set.
 */
static unsigned short int argument_enumset_table_vec[] =
  {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    25,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    26,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    27,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    28,
    0,
    0,
    0,
    0,
    29,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    43,
    0,
    81,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    3,
    4,
    5,
    0,
    0,
    7,
    0,
    8,
    0,
    0,
    9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    11,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    13,
    36,
    14,
    0,
    0,
    0,
    0,
    15,
    0,
    0,
    0,
    0,
    16,
    0,
    0,
    0,
    17,
    111,
    0,
    19,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    5,
    0,
    0,
    21,
    0,
    102,
    0,
    104,
    0,
    0,
    22,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    23,
    0,
    24,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    103,
    0,
    31,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    102,
    0,
    0,
    0,
    0,
    0,
    99,
    32,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    33,
    0,
    0,
    34,
    104,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    35,
    0,
    0,
    0,
    0,
    36,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    39,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    94,
    0,
    40,
    0,
    0,
    0,
    41,
    0,
    0,
    0,
    0,
    42,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    44,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    45,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    46,
    47,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    112,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    49,
    0,
    0,
    0,
    50,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    51,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    52,
    0,
    53,
    54,
    55,
    0,
    56,
    0,
    0,
    0,
    0,
    0,
    0,
    37,
    57,
    0,
    0,
    0,
    0,
    58,
    0,
    0,
    0,
    0,
    59,
    0,
    60,
    0,
    0,
    20,
    61,
    0,
    62,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    63,
    64,
    65,
    0,
    0,
    66,
    67,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    68,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    69,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    71,
    72,
    0,
    0,
    0,
    0,
    73,
    0,
    0,
    74,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    75,
    76,
    77,
    0,
    0,
    78,
    96,
    0,
    79,
    97,
    80,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    70,
    0,
    0,
    82,
    0,
    0,
    83,
    84,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    85,
    86,
    87,
    88,
    89,
    0,
    0,
    48,
    90,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    106,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    107,
    0,
    108,
    105,
    0,
    0,
    109,
    90,
    110,
    0,
    91,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    95,
    0,
    0,
    0,
    0,
    6,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    48,
    0,
    97,
    98,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    38,
    0,
    0,
    0,
    100,
    101,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    18,
  };
externaldef(uil_sym_glbl) unsigned short int *argument_enumset_table =
		argument_enumset_table_vec;
/*
 * Enumeration value table, accessed by sym_k_..._enumval code. Each entry is
 * the actual value associated with the code.
 */
static int enumval_values_table_vec[] =
  {
  0,
  Always,
  DtHELP_AS_NEEDED_SCROLLBARS,
  DtHELP_EXECUTE_ALL,
  DtHELP_EXECUTE_NONE,
  DtHELP_EXECUTE_QUERY_ALL,
  DtHELP_EXECUTE_QUERY_UNALIASED,
  DtHELP_NO_SCROLLBARS,
  DtHELP_STATIC_SCROLLBARS,
  DtHELP_TYPE_DYNAMIC_STRING,
  DtHELP_TYPE_FILE,
  DtHELP_TYPE_MAN_PAGE,
  DtHELP_TYPE_STRING,
  DtHELP_TYPE_TOPIC,
  DtSHADOW_ETCHED_IN,
  DtSHADOW_ETCHED_OUT,
  DtSHADOW_IN,
  DtSHADOW_OUT,
  DtTERM_CHAR_CURSOR_BAR,
  DtTERM_CHAR_CURSOR_BOX,
  DtTERM_CHAR_CURSOR_INVISIBLE,
  ExmSHAPE_OVAL,
  ExmSHAPE_RECTANGLE,
  FALSE,
  IconicState,
  LineDoubleDash,
  LineOnOffDash,
  LineSolid,
  MWM_DECOR_ALL,
  MWM_DECOR_BORDER,
  MWM_DECOR_MAXIMIZE,
  MWM_DECOR_MENU,
  MWM_DECOR_MINIMIZE,
  MWM_DECOR_RESIZEH,
  MWM_DECOR_TITLE,
  MWM_FUNC_ALL,
  MWM_FUNC_CLOSE,
  MWM_FUNC_MOVE,
  MWM_FUNC_RESIZE,
  MWM_INPUT_FULL_APPLICATION_MODAL,
  MWM_INPUT_MODELESS,
  MWM_INPUT_PRIMARY_APPLICATION_MODAL,
  MWM_INPUT_SYSTEM_MODAL,
  NormalState,
  NotUseful,
  TRUE,
  WhenMapped,
  Xm1000TH_INCHES,
  Xm100TH_FONT_UNITS,
  Xm100TH_MILLIMETERS,
  Xm100TH_POINTS,
  XmABSOLUTE,
  XmADD_MODE,
  XmALIGNMENT_BASELINE_BOTTOM,
  XmALIGNMENT_BASELINE_TOP,
  XmALIGNMENT_BEGINNING,
  XmALIGNMENT_CENTER,
  XmALIGNMENT_CONTENTS_BOTTOM,
  XmALIGNMENT_CONTENTS_TOP,
  XmALIGNMENT_END,
  XmALIGNMENT_UNSPECIFIED,
  XmALIGNMENT_WIDGET_BOTTOM,
  XmALIGNMENT_WIDGET_TOP,
  XmANY_ICON,
  XmAPPEND,
  XmAPPLICATION_DEFINED,
  XmARROWS_BEGINNING,
  XmARROWS_DECREMENT_SENSITIVE,
  XmARROWS_DEFAULT_SENSITIVITY,
  XmARROWS_END,
  XmARROWS_FLAT_BEGINNING,
  XmARROWS_FLAT_END,
  XmARROWS_HORIZONTAL,
  XmARROWS_INCREMENT_SENSITIVE,
  XmARROWS_INSENSITIVE,
  XmARROWS_SENSITIVE,
  XmARROWS_SPLIT,
  XmARROWS_VERTICAL,
  XmARROW_DOWN,
  XmARROW_LEFT,
  XmARROW_RIGHT,
  XmARROW_UP,
  XmAS_IS,
  XmAS_NEEDED,
  XmATTACH_FORM,
  XmATTACH_NONE,
  XmATTACH_OPPOSITE_FORM,
  XmATTACH_OPPOSITE_WIDGET,
  XmATTACH_POSITION,
  XmATTACH_SELF,
  XmATTACH_WIDGET,
  XmAUTOMATIC,
  XmAUTO_DRAG_DISABLED,
  XmAUTO_DRAG_ENABLED,
  XmAUTO_SELECT,
  XmAlwaysOpen,
  XmBACKGROUND_COLOR,
  XmBELL,
  XmBOTTOM,
  XmBOTTOM_LEFT,
  XmBOTTOM_RIGHT,
  XmBOTTOM_TO_TOP,
  XmBOTTOM_TO_TOP_LEFT_TO_RIGHT,
  XmBOTTOM_TO_TOP_RIGHT_TO_LEFT,
  XmBROWSE_SELECT,
  XmCELLS,
  XmCENTER,
  XmCENTIMETERS,
  XmCLIP_WINDOW,
  XmCLOSEST,
  XmCOLLAPSED,
  XmCOMBO_BOX,
  XmCOMMAND_ABOVE_WORKSPACE,
  XmCOMMAND_BELOW_WORKSPACE,
  XmCOMMAND_WINDOW,
  XmCONSTANT,
  XmClosed,
  XmDEFAULT_DIRECTION,
  XmDESTROY,
  XmDETAIL,
  XmDIALOG_APPLICATION_MODAL,
  XmDIALOG_CANCEL_BUTTON,
  XmDIALOG_COMMAND,
  XmDIALOG_DEFAULT_BUTTON,
  XmDIALOG_ERROR,
  XmDIALOG_FILE_SELECTION,
  XmDIALOG_FULL_APPLICATION_MODAL,
  XmDIALOG_HELP_BUTTON,
  XmDIALOG_INFORMATION,
  XmDIALOG_MESSAGE,
  XmDIALOG_MESSAGE_LABEL,
  XmDIALOG_MODELESS,
  XmDIALOG_OK_BUTTON,
  XmDIALOG_PRIMARY_APPLICATION_MODAL,
  XmDIALOG_PROMPT,
  XmDIALOG_QUESTION,
  XmDIALOG_SELECTION,
  XmDIALOG_SEPARATOR,
  XmDIALOG_SYMBOL_LABEL,
  XmDIALOG_SYSTEM_MODAL,
  XmDIALOG_TEMPLATE,
  XmDIALOG_WARNING,
  XmDIALOG_WORKING,
  XmDIALOG_WORK_AREA,
  XmDISTRIBUTE_SPREAD,
  XmDISTRIBUTE_TIGHT,
  XmDOUBLE_DASHED_LINE,
  XmDOUBLE_LINE,
  XmDO_NOTHING,
  XmDROP_DOWN_COMBO_BOX,
  XmDROP_DOWN_LIST,
  XmEACH_SIDE,
  XmETCHED_LINE,
  XmEXCLUSIVE_TAB_GROUP,
  XmEXPANDED,
  XmEXPLICIT,
  XmEXTENDED_SELECT,
  XmFILE_ANY_TYPE,
  XmFILE_DIRECTORY,
  XmFILE_REGULAR,
  XmFILL_FLUSH,
  XmFILL_RAGGED,
  XmFILL_UNSPECIFIED,
  XmFIRST_FIT,
  XmFIRST_POSITION,
  XmFONT_IS_FONT,
  XmFONT_IS_FONTSET,
  XmFONT_UNITS,
  XmFOREGROUND_COLOR,
  XmFRAME_GENERIC_CHILD,
  XmFRAME_TITLE_CHILD,
  XmFRAME_WORKAREA_CHILD,
  XmFillAll,
  XmFillMajor,
  XmFillMinor,
  XmFillNone,
  XmGENERIC_CHILD,
  XmGRID,
  XmGROW_BALANCED,
  XmGROW_MAJOR,
  XmGROW_MINOR,
  XmHORIZONTAL,
  XmHOR_SCROLLBAR,
  XmHidden,
  XmINCHES,
  XmINDETERMINATE,
  XmINDICATOR_BOX,
  XmINDICATOR_CHECK,
  XmINDICATOR_CHECK_BOX,
  XmINDICATOR_CROSS,
  XmINDICATOR_CROSS_BOX,
  XmINDICATOR_FILL,
  XmINDICATOR_NONE,
  XmINHERIT_POLICY,
  XmINVALID_MATCH_BEHAVIOR,
  XmIconBottom,
  XmIconLeft,
  XmIconNone,
  XmIconOnly,
  XmIconRight,
  XmIconTop,
  XmLARGE_ICON,
  XmLAST_POSITION,
  XmLEFT,
  XmLEFT_TO_RIGHT,
  XmLEFT_TO_RIGHT_BOTTOM_TO_TOP,
  XmLEFT_TO_RIGHT_TOP_TO_BOTTOM,
  XmLOAD_DEFERRED,
  XmLOAD_IMMEDIATE,
  XmListMode,
  XmMAJOR_TAB,
  XmMARQUEE,
  XmMARQUEE_EXTEND_BOTH,
  XmMARQUEE_EXTEND_START,
  XmMAX_ON_BOTTOM,
  XmMAX_ON_LEFT,
  XmMAX_ON_RIGHT,
  XmMAX_ON_TOP,
  XmMAX_SIDE,
  XmMENU_BAR,
  XmMENU_OPTION,
  XmMENU_POPUP,
  XmMENU_PULLDOWN,
  XmMESSAGE_WINDOW,
  XmMILLIMETERS,
  XmMINOR_TAB,
  XmMIN_SIDE,
  XmMULTICLICK_DISCARD,
  XmMULTICLICK_KEEP,
  XmMULTIPLE_SELECT,
  XmMULTI_LINE_EDIT,
  XmNEAR_BORDER,
  XmNEAR_SLIDER,
  XmNONE,
  XmNORMAL_MODE,
  XmNOT_SELECTED,
  XmNO_AUTO_SELECT,
  XmNO_LINE,
  XmNO_ORIENTATION,
  XmNO_PACKING,
  XmNO_SCROLL,
  XmNUMERIC,
  XmN_OF_MANY,
  XmONE_BASED,
  XmONE_OF_MANY,
  XmONE_OF_MANY_DIAMOND,
  XmONE_OF_MANY_ROUND,
  XmOUTLINE,
  XmOUTLINE_BUTTON_ABSENT,
  XmOUTLINE_BUTTON_PRESENT,
  XmOWN_ALWAYS,
  XmOWN_MULTIPLE,
  XmOWN_NEVER,
  XmOWN_POSSIBLE_MULTIPLE,
  XmOpen,
  XmPACK_COLUMN,
  XmPACK_NONE,
  XmPACK_TIGHT,
  XmPAGE,
  XmPAGE_SCROLLER,
  XmPER_SHELL,
  XmPER_WIDGET,
  XmPIXELS,
  XmPIXMAP,
  XmPIXMAP_BOTTOM,
  XmPIXMAP_LEFT,
  XmPIXMAP_NONE,
  XmPIXMAP_ONLY,
  XmPIXMAP_OVERLAP_ONLY,
  XmPIXMAP_RIGHT,
  XmPIXMAP_TOP,
  XmPLACE_ABOVE_SELECTION,
  XmPLACE_BELOW_SELECTION,
  XmPLACE_TOP,
  XmPOINTER,
  XmPOINTS,
  XmPOSITION_INDEX,
  XmPOSITION_VALUE,
  XmQUICK_NAVIGATE,
  XmRELATIVE,
  XmRESIZE_ANY,
  XmRESIZE_GROW,
  XmRESIZE_IF_POSSIBLE,
  XmRESIZE_NONE,
  XmRIGHT,
  XmRIGHT_TO_LEFT,
  XmRIGHT_TO_LEFT_BOTTOM_TO_TOP,
  XmRIGHT_TO_LEFT_TOP_TO_BOTTOM,
  XmROUND_MARK,
  XmSCROLL_HOR,
  XmSCROLL_VERT,
  XmSELECTED,
  XmSELECT_ALL,
  XmSELECT_LINE,
  XmSELECT_PARAGRAPH,
  XmSELECT_POSITION,
  XmSELECT_WHITESPACE,
  XmSELECT_WORD,
  XmSET,
  XmSHADOWED_BACKGROUND,
  XmSHADOW_ETCHED_IN,
  XmSHADOW_ETCHED_IN_DASH,
  XmSHADOW_ETCHED_OUT,
  XmSHADOW_ETCHED_OUT_DASH,
  XmSHADOW_IN,
  XmSHADOW_OUT,
  XmSINGLE,
  XmSINGLE_DASHED_LINE,
  XmSINGLE_LINE,
  XmSINGLE_LINE_EDIT,
  XmSINGLE_SELECT,
  XmSLIDER,
  XmSMALL_ICON,
  XmSNAP_TO_GRID,
  XmSOLID,
  XmSPATIAL,
  XmSPIRAL,
  XmSTATIC,
  XmSTATUS_AREA,
  XmSTICKY_TAB_GROUP,
  XmSTRING,
  XmSTRING_COMPONENT_CHARSET,
  XmSTRING_COMPONENT_DIRECTION,
  XmSTRING_COMPONENT_LAYOUT_POP,
  XmSTRING_COMPONENT_LAYOUT_PUSH,
  XmSTRING_COMPONENT_LOCALE,
  XmSTRING_COMPONENT_LOCALE_TEXT,
  XmSTRING_COMPONENT_RENDITION_BEGIN,
  XmSTRING_COMPONENT_RENDITION_END,
  XmSTRING_COMPONENT_SEPARATOR,
  XmSTRING_COMPONENT_TAB,
  XmSTRING_COMPONENT_TEXT,
  XmSTRING_COMPONENT_UNKNOWN,
  XmSTRING_COMPONENT_WIDECHAR_TEXT,
  XmSTRING_DIRECTION_DEFAULT,
  XmSTRING_DIRECTION_L_TO_R,
  XmSTRING_DIRECTION_R_TO_L,
  XmSTRING_DIRECTION_UNSET,
  XmScaleMode,
  XmTABS_BASIC,
  XmTABS_BEVELED,
  XmTABS_BOTTOM_TO_TOP,
  XmTABS_LEFT_TO_RIGHT,
  XmTABS_ON_BOTTOM,
  XmTABS_ON_LEFT,
  XmTABS_ON_RIGHT,
  XmTABS_ON_TOP,
  XmTABS_RIGHT_TO_LEFT,
  XmTABS_ROUNDED,
  XmTABS_SQUARED,
  XmTABS_STACKED,
  XmTABS_STACKED_STATIC,
  XmTABS_TOP_TO_BOTTOM,
  XmTAB_EDGE_BOTTOM_RIGHT,
  XmTAB_EDGE_TOP_LEFT,
  XmTAB_GROUP,
  XmTAB_ORIENTATION_DYNAMIC,
  XmTEAR_OFF_DISABLED,
  XmTEAR_OFF_ENABLED,
  XmTHERMOMETER,
  XmTHUMB_MARK,
  XmTOGGLE_BOOLEAN,
  XmTOGGLE_INDETERMINATE,
  XmTOP,
  XmTOP_LEFT,
  XmTOP_RIGHT,
  XmTOP_TO_BOTTOM,
  XmTOP_TO_BOTTOM_LEFT_TO_RIGHT,
  XmTOP_TO_BOTTOM_RIGHT_TO_LEFT,
  XmTOUCH_ONLY,
  XmTOUCH_OVER,
  XmTROUGH_COLOR,
  XmTreeCompressLeaves,
  XmTreeCompressNone,
  XmTreeDirect,
  XmTreeLadder,
  XmUNMAP,
  XmUNPOST,
  XmUNPOST_AND_REPLAY,
  XmUNSET,
  XmVARIABLE,
  XmVERTICAL,
  XmVERT_SCROLLBAR,
  XmWORK_AREA,
  XmZERO_BASED,
  };
externaldef(uil_sym_glbl) int *enumval_values_table =
		enumval_values_table_vec;
